### ISSUE TITLE
Datatable headers on Person#show

### ISSUE THREAD

**Issue by kgf** [ReadyResponder/ReadyResponder#540]
On the person#show page, there are datatables for Availabilities and Timecards. When you first open the page and unroll the accordion, the table headers are not displayed correctly. They look like this
<img width="1367" alt="screen shot 2017-10-09 at 11 43 05 am" src="https://user-images.githubusercontent.com/2431417/31346427-127886da-ace7-11e7-9acb-01cb1e3d357f.png">
If you click on one of the headers, causing click to sort, it all straightens out properly.
We'd like it to be correct from the beginning !

Thanks

**Comment by estevanjantsk** [comment]
Hi! =), may you guys assign this issue to me, please?

**Comment by kgf** [comment]
Sure, thanks for your help @estevanjantsk

**Comment by goldenhub77** [comment]
@kgf @estevanjantsk while working on my current issue regarding timecards I was forced to resolve this issue as well. This datatable was rendering as generic when it is not.

**Comment by goldenhub77** [comment]
@kgf @estevanjantsk refer to PR for https://github.com/ReadyResponder/ReadyResponder/issues/538 for resolution.

**Comment by kgf** [comment]
Actually, @goldenhub77  is referring to Issue #538, rather than PR #538, in case you were looking.

**Comment by goldenhub77** [comment]
Refer to https://github.com/ReadyResponder/ReadyResponder/pull/543

**Comment by kgf** [comment]
Turns out this may not have been resolved.

**Comment by goldenhub77** [comment]
@kgf @estevanjantsk It turns out my initial theory was wrong and this issue is not resolved. I can tell you its not an issue with the data table render or configurations. I suspect the accordion class to be playing a role or how that is being rendered. We may want to switch to a tabbed UI as it works well on other pages especially with the tables.

**Comment by kgf** [comment]
This actually IS working on development. I'm going to close this, we can re-open as needed.
